# [general]

[window]
opacity = 1.0

[font]
builtin_box_drawing = true
normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"
size=12

[cursor.style]
shape = "Block"
blinking = "Off"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[selection]
save_to_clipboard = true
